spring:
  jpa:
    show-sql: true    # 전송 쿼리 확인
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true  # 테이블 생성 후에 data.sql 생성

  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 경로 설정